blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/mpimedia/mpi-application-standards
    about: Check the shared standards repository for coding guidelines
